#!/usr/bin/env python3
"""Turns assets/branding/kreative-kompas-logo.svg into the flat outlines the
engine extrudes into the 3D logo (engine/src/LogoOutlines.inc).

    python3 -m pip install svgpathtools shapely
    python3 tools/branding/make_logo_outlines.py

Run it again after changing the SVG. Each SVG path becomes one logo piece.
Pieces with holes (the crown's loop) are split into hole-free halves, and
the needle halves are split along the needle's axis so the engine can raise
them into a faceted roof. Coordinates: the hub is the origin, the ring's
outer radius is 1, +Y is up.
"""
import pathlib
import xml.etree.ElementTree as ET

from shapely.geometry import Polygon
from shapely.ops import orient, split
from shapely.geometry import LineString
from svgpathtools import parse_path

ROOT = pathlib.Path(__file__).resolve().parents[2]
SVG = ROOT / "assets/branding/kreative-kompas-logo.svg"
OUT = ROOT / "engine/src/LogoOutlines.inc"

HUB = (249.11, 305.52)       # the purple centre circle
RING_OUTER = 453.79 - 249.11  # right arc's outer edge
STEP = 1.5                    # SVG units between samples on curves

# Paths in document order, named. The hidden (display:none) hub ring is skipped.
NAMES = ["needle_north", "needle_south", None, "k_right", "k_left", "crown_stem", "crown_loop",
         "ring_top", "ring_right", "ring_bottom", "ring_left"]
COLORS = {"st0": "kOrange", "st1": "kPurple", "st3": "kOrange"}


def to_logo(z):
    return ((z.real - HUB[0]) / RING_OUTER, (HUB[1] - z.imag) / RING_OUTER)


def path_rings(d):
    """Every closed subpath of `d`, sampled into a point list."""
    rings = []
    for sub in parse_path(d).continuous_subpaths():
        pts = []
        for seg in sub:
            n = max(1, int(seg.length() / STEP)) if seg.__class__.__name__ != "Line" else 1
            for i in range(n):
                pts.append(to_logo(seg.point(i / n)))
        rings.append(pts)
    return rings


def polygon_from(d):
    rings = [Polygon(r).buffer(0) for r in path_rings(d)]
    rings.sort(key=lambda p: -p.area)
    shape = rings[0]
    for hole in rings[1:]:
        shape = shape.difference(hole) if shape.contains(hole.representative_point()) else shape.union(hole)
    return shape


def simple_parts(shape, cut_x=None):
    """Hole-free, counter-clockwise polygons covering `shape`."""
    parts = list(shape.geoms) if hasattr(shape, "geoms") else [shape]
    out = []
    for p in parts:
        if cut_x is not None or p.interiors:
            x = cut_x if cut_x is not None else p.centroid.x
            halves = split(p, LineString([(x, -5), (x, 5)]))
            for half in halves.geoms:
                out += simple_parts(half)
        else:
            out.append(orient(p.simplify(0.0004), 1.0))
    return out


def main():
    ns = {"svg": "http://www.w3.org/2000/svg"}
    tree = ET.parse(SVG)
    paths = [e for e in tree.iter() if e.tag.endswith("path")]
    assert len(paths) == len(NAMES), f"expected {len(NAMES)} paths, SVG has {len(paths)}"
    circle = next(e for e in tree.iter() if e.tag.endswith("circle"))

    lines = [
        "// Generated by tools/branding/make_logo_outlines.py from",
        "// assets/branding/kreative-kompas-logo.svg. Do not edit by hand.",
        "// Units: hub at the origin, ring outer radius 1, +Y up.",
        "",
        "const std::vector<GeneratedPiece> kGeneratedPieces = {",
    ]
    for el, name in zip(paths, NAMES):
        if name is None:
            continue
        shape = polygon_from(el.get("d"))
        cut = 0.0 if name.startswith("needle") else None
        parts = simple_parts(shape, cut)
        color = COLORS[el.get("class")]
        lines.append(f'    {{ "{name}", {color}, {{')
        for part in parts:
            coords = list(part.exterior.coords)[:-1]
            body = ", ".join(f"{{{x:.5f}f, {y:.5f}f}}" for x, y in coords)
            lines.append(f"        {{ {body} }},")
        lines.append("    } },")
    lines.append("};")
    r = float(circle.get("r")) / RING_OUTER
    lines.append(f"constexpr float kHubRadius = {r:.5f}f;")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)} (hub radius {r:.4f})")


if __name__ == "__main__":
    main()
